### PR TITLE
fix(SMenu): 修复了SMenu中STip中文会换行

### PR DESCRIPTION
**Pull request by ZhengLongBing**
修复前:

修复后:

### CODE REVIEW

**Comment by syf20020816** [comment]
换行是被允许的

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Longbing Zheng ***@***.***>
Sent: Wednesday, December 27, 2023 12:26:47 PM
To: Surrealism-All/SurrealismUI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Surrealism-All/SurrealismUI] fix(SMenu): 修复了SMenu中STip中文会换行 (PR #15)


修复前:
[1703650709897-2023-12-27-12:18:30.png]<https://camo.githubusercontent.com/33059b49f36ced4a49484766fbd8e5847cba1f1c97b8deb130b903a8f5a8e75e/68747470733a2f2f666173746c792e6a7364656c6976722e6e65742f67682f5a68656e674c6f6e6742696e672f696d61676573406d61696e2f70696374757265732f313730333635303730393839372d323032332d31322d32372d31323a31383a33302e706e67>

修复后:
[1703650697983-2023-12-27-12:18:18.png]<https://camo.githubusercontent.com/3dcbac06ddb842b434fa547d571fe4676a38df5c7a604d96c82e483b78b0b942/68747470733a2f2f666173746c792e6a7364656c6976722e6e65742f67682f5a68656e674c6f6e6742696e672f696d61676573406d61696e2f70696374757265732f313730333635303639373938332d323032332d31322d32372d31323a31383a31382e706e67>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/Surrealism-All/SurrealismUI/pull/15

Commit Summary

  *   da07d00<https://github.com/Surrealism-All/SurrealismUI/pull/15/commits/da07d00fe938d819d0f8636962226284823d72d7> fix(SMenu): 修复了SMenu中STip中文会换行

File Changes

(1 file<https://github.com/Surrealism-All/SurrealismUI/pull/15/files>)

  *   M src/menu/menu.slint<https://github.com/Surrealism-All/SurrealismUI/pull/15/files#diff-2ab13005e1f73b60828b7ad76aef24a1bfcba59fb6853da19e813fedce21c56c> (1)

Patch Links:

  *   https://github.com/Surrealism-All/SurrealismUI/pull/15.patch
  *   https://github.com/Surrealism-All/SurrealismUI/pull/15.diff

―

**Comment by ZhengLongBing** [comment]
没有添加
```css
wrap: no-wrap;
```

是这样的情况：




输入中文会换行，而英文却不会。

**Comment by ZhengLongBing** [comment]
加入
```css
wrap: no-wrap;
```
起码可以保证中英文统一不换行

**Comment by syf20020816** [comment]
关于中文换行的主要原因是slint内对于中文的支持，对于英文的分词句子和中文不同，对于STip的换行方式还需要更深的控制，考虑在下个版本中进行处理

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ZhengLongBing** [comment]
好的

**Pull request closed without merging**
