### PR TITLE
fix: repetitive `Close_one` member in property `icons`

### PR DESCRIPTION
**Pull request by Serein207**
This error may cause redeclaration error in cpp, but not cause in rust (? I guess :smiling_face_with_tear:

### CODE REVIEW

**Comment by syf20020816** [comment]
is that can not use in preview or can not use after compile
can you give me more details, I do not use c++
if that display well after compile the merge is not necessary

**Comment by Serein207** [comment]
It compiled error
image

**Comment by syf20020816** [comment]
can other Icons pass the compiler(such as Preview_one, Down_one)

**Comment by Serein207** [comment]
There is no problem with other icons.

The compilation failed simply because `Close_one` was written twice in the code, which would cause two members with the same name to appear in the Icon class in the .h file compiled by slint.

So, removing any one of them will make the code compile. :smile:

**Comment by syf20020816** [comment]
> There is no problem with other icons.
> 
> The compilation failed simply because `Close_one` was written twice in the code, which would cause two members with the same name to appear in the Icon class in the .h file compiled by slint.
> 
> So, removing any one of them will make the code compile. 😄

ok I see that, merge

**Pull request merged**
